title: 'Matteo Duranti''s Personal WebSite'
default_lang: null
author:
  name: 'Matteo Duranti'
  email: bozzo1983@gmail.com
taxonomies:
  - category
  - tag
metadata: null
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
