enabled: true
production-mode: true
grid-size: grid-xl
header-fixed: true
header-animated: true
header-dark: true
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo: {  }
custom_logo_mobile: {  }
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/my-quark, user/themes/quark]
